package com.example.bookmyshow.model;

import jakarta.persistence.*;
import lombok.Getter;

/**
 * Seat is a JPA Entity representing a physical seat inside a Screen.
 *
 * IMPORTANT DESIGN NOTES:
 * - This is a persistence model (Entity), NOT an API model.
 * - Business rules are enforced via controlled constructors.
 */
@Entity
@Getter
@Table(name = "seats")
public class Seat {

    /**
     * Primary Key
     * Auto-generated by the database (IDENTITY strategy).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Logical seat number (e.g., 1, 2, 3...)
     * Not marked unique here because uniqueness is usually
     * enforced at (screen_id + seat_number) level.
     */
    private Long seatNumber;

    /**
     * Enum stored as STRING instead of ORDINAL.
     * WHY?
     * - ORDINAL breaks if enum order changes
     * - STRING is safer and readable in DB
     */
    @Enumerated(EnumType.STRING)
    private SeatType seatType;

    /**
     * Many seats belong to ONE screen.
     *
     * FetchType.LAZY:
     * - Screen data is NOT loaded unless accessed
     * - Prevents unnecessary joins and improves performance
     *
     * @JoinColumn creates screen_id FK in seats table.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "screen_id", nullable = false)
    private Screen screen;

    /**
     * REQUIRED by Hibernate / JPA.
     *
     * WHY THIS CONSTRUCTOR EXISTS:
     * - Hibernate creates entities using reflection / proxies
     * - It CANNOT call parameterized constructors
     * - A no-args constructor is mandatory
     *
     * WHY IT IS 'protected':
     * - Allows Hibernate to access it
     * - Prevents developers from creating invalid Seat objects
     *
     * ❌ public  -> allows invalid domain objects
     * ❌ private -> breaks Hibernate proxying
     * ✅ protected -> PERFECT balance
     */
    protected Seat() {
    }

    /**
     * Business-safe constructor.
     *
     * Forces creation of a valid Seat:
     * - seatNumber is mandatory
     * - seatType is mandatory
     * - screen association is mandatory
     *
     * This prevents accidental creation of incomplete entities.
     */
    public Seat(Long seatNumber, SeatType seatType, Screen screen) {
        this.seatNumber = seatNumber;
        this.seatType = seatType;
        this.screen = screen;
    }
}
