package com.example.bookmyshow.model;

import jakarta.persistence.*;
import lombok.Getter;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * ============================
 * SHOW ENTITY (AGGREGATE ROOT)
 * ============================
 *
 * 👉 This entity represents a Movie Show.
 * 👉 It is the AGGREGATE ROOT in DDD terms.
 * 👉 It owns the lifecycle of ShowSeat.
 *
 * VERY IMPORTANT CONCEPTS USED HERE:
 * 1️⃣ Cascade
 * 2️⃣ Orphan Removal
 * 3️⃣ Lazy Loading
 * 4️⃣ Controlled object creation (no setters)
 *
 * Interview tip:
 * "Show is the parent entity and ShowSeat cannot exist without it."
 */

@Entity
@Table(name = "shows")
@Getter
public class Show {

    /**
     * Primary Key
     * Auto-generated by DB
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Movie name for this show
     */
    @Column(nullable = false)
    private String movieName;

    /**
     * Show start time
     */
    @Column(nullable = false)
    private LocalDateTime startTime;

    /**
     * ===============================
     * ONE-TO-MANY RELATIONSHIP
     * ===============================
     *
     * A Show has many ShowSeats
     *
     * mappedBy = "show"
     * -----------------
     * • Indicates this is the inverse side of the relationship
     * • Foreign key lives in ShowSeat table (show_id)
     *
     * fetch = LAZY
     * ------------
     * • Seats are NOT loaded unless explicitly accessed
     * • Prevents N+1 problem in listing APIs
     *
     * cascade = ALL
     * -------------
     * • Persist Show → Seats saved automatically
     * • Delete Show → Seats deleted automatically
     * • Merge Show → Seats merged automatically
     *
     * orphanRemoval = true
     * --------------------
     * • If a seat is REMOVED from this list,
     *   it is DELETED from DB
     * • Prevents orphan rows
     *
     * BUSINESS MEANING:
     * -----------------
     * ShowSeat has NO MEANING without Show.
     * Its lifecycle is completely controlled by Show.
     */
    @OneToMany(
            mappedBy = "show",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.LAZY
    )
    private List<ShowSeat> showSeats = new ArrayList<>();

    private boolean isWeekend;

    private boolean isSurgeActive;


    /**
     * ===============================
     * JPA-REQUIRED PROTECTED CONSTRUCTOR
     * ===============================
     *
     * • Required by Hibernate
     * • Prevents accidental creation outside domain
     */
    protected Show() {}

    /**
     * ===============================
     * DOMAIN-SAFE CONSTRUCTOR
     * ===============================
     *
     * Forces valid Show creation
     */
    public Show(String movieName, LocalDateTime startTime) {
        this.movieName = movieName;
        this.startTime = startTime;
    }

    /**
     * ===============================
     * DOMAIN METHOD: ADD SEAT
     * ===============================
     *
     * WHY THIS METHOD?
     * ----------------
     * • Ensures bidirectional consistency
     * • Avoids forgetting to set parent
     *
     * Interview:
     * "Always synchronize both sides of bidirectional relationships."
     */
    public void addSeat(ShowSeat seat) {
        showSeats.add(seat);
        seat.assignShow(this);
    }

    /**
     * ===============================
     * DOMAIN METHOD: REMOVE SEAT
     * ===============================
     *
     * IMPORTANT:
     * ----------
     * Because orphanRemoval = true:
     * Removing seat from this list →
     * DELETE FROM show_seats table
     */
    public void removeSeat(ShowSeat seat) {
        showSeats.remove(seat);
        seat.assignShow(null);
    }

}
